# Generated by Django 2.2.9 on 2020-04-17 08:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.ArticleType')),
            ],
        ),
    ]
