# Generated by Django 2.2.9 on 2020-05-27 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecount',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_count', to='contenttypes.ContentType'),
        ),
    ]
